name: firegnn
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - GitPython==3.1.46
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PyYAML==6.0.3
    - Pygments==2.19.2
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.12.1
    - ase==3.27.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - bibtexparser==1.4.3
    - blake3==1.0.8
    - boto3==1.42.30
    - botocore==1.42.30
    - cached_path==1.8.1
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - click==8.3.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - decorator==5.2.1
    - dm-tree==0.1.8
    - e3nn==0.5.9
    - emmet-core==0.86.0rc1
    - exceptiongroup==1.3.1
    - filelock==3.20.3
    - fonttools==4.61.1
    - frozenlist==1.8.0
    - fsspec==2026.1.0
    - gitdb==4.0.12
    - google-api-core==2.29.0
    - google-auth==2.47.0
    - google-cloud-core==2.5.0
    - google-cloud-storage==3.8.0
    - google-crc32c==1.8.0
    - google-resumable-media==2.8.0
    - googleapis-common-protos==1.72.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface_hub==1.3.2
    - idna==3.11
    - jmespath==1.0.1
    - joblib==1.5.3
    - kiwisolver==1.4.9
    - latexcodec==3.0.1
    - markdown-it-py==4.0.0
    - matplotlib==3.10.8
    - mdurl==0.1.2
    - monty==2025.3.3
    - mp-api==0.45.13
    - mpmath==1.3.0
    - msgpack==1.1.2
    - multidict==6.7.0
    - narwhals==2.15.0
    - networkx==3.4.2
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.6.77
    - opt-einsum-fx==0.1.4
    - opt_einsum==3.4.0
    - orb-models==0.5.5
    - orjson==3.11.5
    - packaging==25.0
    - palettable==3.3.3
    - pandas==2.3.3
    - pillow==12.1.0
    - platformdirs==4.5.1
    - plotly==6.5.2
    - propcache==0.4.1
    - proto-plus==1.27.0
    - protobuf==6.33.4
    - psutil==7.2.1
    - py==1.11.0
    - pyasn1==0.6.2
    - pyasn1_modules==0.4.2
    - pybtex==0.25.1
    - pydantic==2.12.5
    - pydantic-settings==2.12.0
    - pydantic_core==2.41.5
    - pymatgen==2025.10.7
    - pymatgen-io-validation==0.1.2
    - pyparsing==3.3.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - requests==2.32.5
    - retry==0.9.2
    - rich==13.9.4
    - rsa==4.9.1
    - ruamel.yaml==0.19.1
    - s3transfer==0.16.0
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - sentry-sdk==2.50.0
    - shellingham==1.5.4
    - six==1.17.0
    - smart_open==7.5.0
    - smmap==5.0.2
    - spglib==2.7.0
    - sympy==1.14.0
    - tabulate==0.9.0
    - threadpoolctl==3.6.0
    - torch==2.8.0+cu126
    - torch-geometric==2.7.0
    - torch-scatter==2.1.2
    - tqdm==4.67.1
    - triton==3.4.0
    - typer-slim==0.21.1
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - tzdata==2025.3
    - uncertainties==3.2.4
    - urllib3==2.6.3
    - uv==0.9.22
    - wandb==0.24.0
    - wrapt==2.0.1
    - xxhash==3.6.0
    - yarl==1.22.0
